python codec_VR.py decode -o ./rec_imgs/I01dec.png ./bins/I01.bin
python codec_VR.py decode -o ./rec_imgs/I02dec.png ./bins/I02.bin
python codec_VR.py decode -o ./rec_imgs/I03dec.png ./bins/I03.bin
python codec_VR.py decode -o ./rec_imgs/I04dec.png ./bins/I04.bin
python codec_VR.py decode -o ./rec_imgs/I05dec.png ./bins/I05.bin
python codec_VR.py decode -o ./rec_imgs/I06dec.png ./bins/I06.bin
python codec_VR.py decode -o ./rec_imgs/I07dec.png ./bins/I07.bin
python codec_VR.py decode -o ./rec_imgs/I08dec.png ./bins/I08.bin
python codec_VR.py decode -o ./rec_imgs/I09dec.png ./bins/I09.bin
python codec_VR.py decode -o ./rec_imgs/I10dec.png ./bins/I10.bin
python codec_VR.py decode -o ./rec_imgs/I11dec.png ./bins/I11.bin
python codec_VR.py decode -o ./rec_imgs/I12dec.png ./bins/I12.bin
python codec_VR.py decode -o ./rec_imgs/I13dec.png ./bins/I13.bin
python codec_VR.py decode -o ./rec_imgs/I14dec.png ./bins/I14.bin
python codec_VR.py decode -o ./rec_imgs/I15dec.png ./bins/I15.bin
python codec_VR.py decode -o ./rec_imgs/I16dec.png ./bins/I16.bin
python codec_VR.py decode -o ./rec_imgs/I17dec.png ./bins/I17.bin
python codec_VR.py decode -o ./rec_imgs/I18dec.png ./bins/I18.bin
python codec_VR.py decode -o ./rec_imgs/I19dec.png ./bins/I19.bin
python codec_VR.py decode -o ./rec_imgs/I20dec.png ./bins/I20.bin